# Minimal tools configuration for Fly.io deployment
# Exposes only the read-only Query Manager tool.

other_services:
  object_manager: False
  query_manager: True
  semantic_manager: False

# Permit only SELECT queries; block everything else by omission.
# Keep Unknown: False to reject any unrecognized statement types.
sql_statement_permissions:
  - Select: True
  - Unknown: False
